# -*- coding: utf-8 -*-
"""calculadora de tabuada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUlYZOqg71KvKX4f97moVFhj0nNYpPdz
"""

aniversario = 8
numero = 0

while numero <= 100:
    multiplicando = aniversario * numero
    numero+= 1

    if multiplicando > 1000:
        print(f"o numero {multiplicando} é maior que 1000")
    print(multiplicando)