# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yp2rdYxh_vAp6UDl1V41xkz6avLhGjL6
"""

nome = str(input("digite seu nome: "))
idade = int(input("digite sua idade: "))
cpf = float(input("digite seu cpf: "))
dia = int(input("digite o número do dia: "))
local = str(input("digite o local: "))

print("\nanalisando informações....")

print(f"\ndados coletados: seu nome é: {nome}")
print(f"sua idade: {idade}")
print(f"seu cpf: {cpf}")
print(f"hoje é dia: {dia}")
print(f"sua localização atual é: {local}")