# -*- coding: utf-8 -*-
"""primos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1rtJHuRfv-Gwkqems9NU_JXcIPvdQBo
"""

for numero in range(1, 101):
    if numero <= 1:
        print(numero)
        continue

    eh_primo = True

    for i in range(2, int(numero**0.5) + 1):
        if numero % i == 0:
            eh_primo = False
            break

    if eh_primo:
        print(f"O numero ({numero}) é primo")
    else:
        print(f"{numero}")
    if numero % 2 ==0:
        print(f"{numero} é divisivel por 2")